# Generated by Django 5.0 on 2024-01-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_thumbnail_project_logo_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to='projects/static/projects/img/screenshots/'),
        ),
    ]
