# Generated by Django 5.0 on 2024-01-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='static/img/logos/logo-480.png', upload_to='projects/static/projects/img/thumbnails/'),
        ),
    ]
