# Generated by Django 5.0 on 2024-01-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='static/img/logos/portfolio-logo-480.png', upload_to='projects/static/projects/img/logos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='static/img/logos/portfolio-logo-480.png', upload_to='projects/static/projects/img/thumbnails/'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='projects.technology'),
        ),
    ]
