# Generated by Django 5.0 on 2024-01-12 03:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_technology_alter_project_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['rank', django.db.models.functions.text.Lower('name')], 'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AddField(
            model_name='technology',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Backend framework'), (2, 'Frontend framework'), (3, 'Databases and persistence'), (4, 'CSS framework'), (5, 'Misc.')], default=5),
        ),
    ]
