# Generated by Django 5.0 on 2024-01-12 03:27

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_technology_options_technology_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['category', django.db.models.functions.text.Lower('name')], 'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='rank',
            new_name='category',
        ),
    ]
