# Generated by Django 5.0 on 2024-01-12 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_technology_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.IntegerField(choices=[(1, 'Backend framework'), (2, 'Frontend framework'), (3, 'Databases and persistence'), (4, 'CSS framework'), (5, 'Testing framework'), (6, 'Misc.')], default=5),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('bootstrap_icon', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project')),
            ],
        ),
    ]
