# Generated by Django 5.0 on 2024-01-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_technology_category_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['name']},
        ),
    ]
