# Generated by Django 5.0 on 2024-01-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_link_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
