# Generated by Django 5.0.2 on 2024-03-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_logo_alter_project_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='summary',
            new_name='overview',
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.IntegerField(choices=[(1, 'Backend framework'), (2, 'Frontend framework'), (3, 'Databases and persistence'), (4, 'CSS framework'), (5, 'Testing framework'), (6, 'Other')], default=5),
        ),
    ]
