# Generated by Django 5.0.2 on 2024-03-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_description_project_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.IntegerField(choices=[(1, 'Backend framework'), (2, 'Frontend framework'), (3, 'Databases and persistence'), (4, 'Authentication/authorization'), (5, 'CSS framework'), (6, 'Testing framework'), (7, 'Other')], default=5),
        ),
    ]
