# Generated by Django 5.0.2 on 2024-03-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_technology_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.IntegerField(choices=[(1, 'Backend'), (2, 'Frontend'), (3, 'Databases and persistence'), (4, 'Authentication/authorization'), (5, 'Routing and data handling'), (6, 'CSS frameworks'), (7, 'Testing'), (8, 'Other')], default=5),
        ),
    ]
