# Generated by Django 5.0.2 on 2024-03-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_technology_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='structure',
            field=models.TextField(blank=True),
        ),
    ]
