# Generated by Django 5.0 on 2023-12-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='static/img/logos/logo-thumbnail.png', upload_to='blog/static/img/thumbnails/'),
        ),
    ]
