# Generated by Django 5.0 on 2023-12-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_location_post_summary_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
