# Generated by Django 5.0 on 2024-02-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_summary_post_overview_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/blog/img/banners/'),
        ),
    ]
