# Generated by Django 5.0 on 2024-02-09 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/static/blog/img/posts/banners/')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('source', models.CharField(blank=True, max_length=250)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='blog.post')),
            ],
        ),
    ]
