# Generated by Django 5.0 on 2024-03-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_banner_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='blog/static/blog/img/banners/'),
        ),
    ]
