# Generated by Django 5.0.2 on 2024-03-09 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_banner_image_alter_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/img/photos/')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('source', models.CharField(blank=True, max_length=250)),
                ('alt', models.CharField(blank=True, max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.post')),
            ],
        ),
    ]
