# Generated by Django 5.0.2 on 2024-03-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='project',
            new_name='post',
        ),
    ]
