# Generated by Django 5.0.2 on 2024-03-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_photo_slug_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
