# Generated by Django 5.0 on 2023-12-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='static/img/default_thumbnail.png', upload_to='portfolio/static/img/thumbnails/'),
        ),
    ]
