# Generated by Django 5.0 on 2023-12-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='static/img/logos/logo-thumbnail.png', upload_to='portfolio/static/img/thumbnails/'),
        ),
    ]
